# ${PROJECT_NAME}
#
# Doc: https://github.com/yonaskolb/XcodeGen
#

name: ${PROJECT_NAME}

options:
  developmentLanguage: pt-BR
  deploymentTarget:
    iOS: '16.0'

localPackages:
  - Packages/AppNavigationKit
  - Packages/UtilKit
  - Packages/NetworkKit

# packages:
#   SamplePackageName:
#     url: https://github.com/SamplePackageName
#     exactVersion: X.X.X

configs:
  Development: debug
  Production: release

targets:
  ####################
  # Main app
  ####################
  ${PROJECT_NAME}:
    type: application
    platform: iOS
    configFiles:
      Development: Config/dev.xcconfig
      Production: Config/prd.xcconfig
    settings:
      base:
        ASSETCATALOG_COMPILER_APPICON_NAME: $(APP_ICON)
        PRODUCT_NAME: ${PROJECT_NAME}
        ONLY_ACTIVE_ARCH: YES
        DEVELOPMENT_TEAM: $(DEVELOPMENT_TEAM)
        CODE_SIGN_IDENTITY: "iPhone Distribution"
        CODE_SIGN_STYLE: Manual
        PROVISIONING_PROFILE_SPECIFIER: $(PROVISIONING_PROFILE_SPECIFIER)
        SWIFT_VERSION: $(SWIFT_VERSION)
        DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
        CURRENT_PROJECT_VERSION: $(CURRENT_PROJECT_VERSION)
        OTHER_LDFLAGS: ["$(inherited)", "-ObjC"]
        FRAMEWORK_SEARCH_PATHS: ["$(inherited)", "$(PROJECT_DIR)"]
        PRODUCT_BUNDLE_IDENTIFIER: $(BUNDLE_IDENTIFIER)
    sources: 
      - ${PROJECT_NAME}
    resources: 
      - ${PROJECT_NAME}/Application/Resources

    # InfoPlist Configurations
    info:
      path: Config/Info.plist
      properties:
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleIdentifier: $(BUNDLE_IDENTIFIER)
        CFBundleDisplayName: $(APP_DISPLAY_NAME)
        ITSAppUsesNonExemptEncryption: NO
        UIStatusBarStyle: UIStatusBarStyleLightContent
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UILaunchStoryboardName: LaunchScreen
        UIRequiredDeviceCapabilities:
          - armv7
        ENVIRONMENT: $(ENVIRONMENT)
    entitlements:
      path: Config/${PROJECT_NAME}.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.appgroup.sample.${PROJECT_NAME}
    dependencies:
      - package: AppNavigationKit
      - package: UtilKit
      - package: NetworkKit

schemes:
  ${PROJECT_NAME}:
    run:
      config: Development
    archive:
      config: Production
    build:
      targets:
        ${PROJECT_NAME}: all
      parallelizeBuild: true
      buildImplicitDependencies: true
