# Project Template sample
#
# Doc: https://github.com/yonaskolb/XcodeGen
#

name: ProjectTemplate

options:
  developmentLanguage: pt-BR

  deploymentTarget:
    iOS: 16.0

localPackages:
  - Packages/AppNavigationKit
  - Packages/UtilKit
  - Packages/NetworkKit

# packages:
#   SamplePackagenName:
#     url: https://github.com/SamplePackagenName
#     exactVersion: X.X.X

configs:
  Development: debug
  Production: release

targets:

  ####################
  # Main app
  ####################
  ProjectTemplate:
    type: application
    platform: iOS
    configFiles:
      Development: Config/dev.xcconfig
      Production: Config/prd.xcconfig
    settings:
      ASSETCATALOG_COMPILER_APPICON_NAME: $(APP_ICON)
      PRODUCT_NAME: $(PRODUCT_NAME)
      ONLY_ACTIVE_ARCH: YES
      DEVELOPMENT_TEAM: $(DEVELOPMENT_TEAM)
      CODE_SIGN_IDENTITY: iPhone Distribution
      CODE_SIGN_STYLE: Manual
      PROVISIONING_PROFILE_SPECIFIER: $(PROVISIONING_PROFILE_SPECIFIER)
      SWIFT_VERSION: $(SWIFT_VERSION)
      DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
      CURRENT_PROJECT_VERSION: $(CURRENT_PROJECT_VERSION)
      OTHER_LDFLAGS: ["$(inherited)", -ObjC]
      FRAMEWORK_SEARCH_PATHS: ["$(inherited)", "$(PROJECT_DIR)"]
    sources: [ProjectTemplate]
    resources: [ProjectTemplate/Application/Resources]

    # ##############################
    # InfoPlist Configurations
    # ##############################
    info:
      path: Config/Info.plist
      properties:
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleIdentifier: $(BUNDLE_IDENTIFIER)
        CFBundleDisplayName: $(APP_DISPLAY_NAME)
        ITSAppUsesNonExemptEncryption: NO
        UIStatusBarStyle: UIStatusBarStyleLightContent
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait, UIInterfaceOrientationLandscapeLeft, UIInterfaceOrientationLandscapeRight]
        UISupportedInterfaceOrientations~ipad: [UIInterfaceOrientationPortrait, UIInterfaceOrientationPortraitUpsideDown, UIInterfaceOrientationLandscapeLeft, UIInterfaceOrientationLandscapeRight]
        UILaunchStoryboardName: LaunchScreen
        UIRequiredDeviceCapabilities: [armv7]
        ENVIRONMENT: $(ENVIRONMENT)
        UIBackgroundModes: [fetch]
    entitlements:
      path: Config/ProjectTemplate.entitlements
      properties:
        com.apple.security.application-groups: [
          "group.com.appgroup.sample.ProjectTemplate"
        ]
    dependencies:
      - package: AppNavigationKit
      - package: UtilKit
      - package: NetworkKit


schemes:
  ProjectTemplate:
    run:
      config: Development
    archive:
      config: Development
    build:
      targets:
        ProjectTemplate: all
      parallelizeBuild: true
      buildImplicitDependencies: true